### ISSUE TITLE
[Question] How do I install cogs?

### ISSUE THREAD

**Issue by Deses** [PhasecoreX/docker-red-discordbot#100]
I'm completely new to RedBot and i went straight to this docker because it's available in the Unraid Community Apps Store, I've tried running both this and the official documentation but I can't figure out how to install cogs. You explain how to migrate cogs from a normal installation to docker but not how to install them directly here and I'm a bit confused.

Thanks for the help.

**Comment by crovaxon** [comment]
Not really a bug if you ask me :)
I suggest taking a look at the redbot documentation: https://docs.discord.red/en/stable/, specifically the user guides about how to operate redbot.

**Comment by Roxedus** [comment]
https://docs.discord.red/en/stable/cog_guides/downloader.html is the cog you want to use

**Comment by PhasecoreX** [comment]
Right, this repo is for the container around Redbot, not Redbot itself. If you have questions about using Redbot, you can ask them in the official Redbot Discord server https://discord.com/invite/red, or you can browse the documentation listed above.

But yes, you need to load the Downloader cog first before you can load and unload cogs.
