### ISSUE TITLE
You need to update to Python 3.8 to allow future updates

### ISSUE THREAD

**Issue by louga31** [PhasecoreX/docker-red-discordbot#13]

**Comment by PhasecoreX** [comment]
This image is already running Python 3.8.1. See https://github.com/PhasecoreX/docker-red-discordbot/commit/73d2a52d59068fd6f00918b262b2c915cc63fda1. If you aren't seeing Python 3.8.1 when running the command `[p] info`, be sure to pull the latest [`phasecorex/red-discordbot`](https://hub.docker.com/r/phasecorex/red-discordbot) image, and consider adding my [UpdateNotify cog](https://github.com/PhasecoreX/PCXCogs) to your bot to stay up to date on the latest Red-DiscordBot and Docker image versions.
