### ISSUE TITLE
Argument for Develop mode didn't work anymore

### ISSUE THREAD

**Issue by entchen66** [PhasecoreX/docker-red-discordbot#15]
Hey,

I have noticed, that the argument --dev didn't seams to run the bot in develo mode anymore.

Any idea whats going wrong there?

**Comment by PhasecoreX** [comment]
Yeah, I goofed when enancing the `TOKEN` and `PREFIX` environment variable handling. I have added back support for using `EXTRA_ARGS`.

Good catch, and sorry about that! Builds have been completed, so you can pull the new image and get back to developing!

**Comment by entchen66** [comment]
That was fast, thank you :)
