### ISSUE TITLE
uvloop fails

### ISSUE THREAD

**Issue by bleonard252** [PhasecoreX/docker-red-discordbot#16]
The error appears to be "gcc: fatal error: Killed signal terminated program as compilation terminated."

I'm building this on a Raspberry Pi 3B+.

Full log: 
<details><summary>Full log</summary>
<pre>
Running setup.py install for uvloop: started
    Running setup.py install for uvloop: still running...
    Running setup.py install for uvloop: still running...
    Running setup.py install for uvloop: finished with status 'error'
    ERROR: Command errored out with exit status 1:
     command: /data/venv/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-vdffozvt/uvloop/setup.py'"'"'; __file__='"'"'/tmp/pip-install-vdffozvt/uvloop/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-54ysa324/install-record.txt --single-version-externally-managed --compile --install-headers /data/venv/include/site/python3.8/uvloop
         cwd: /tmp/pip-install-vdffozvt/uvloop/
    Complete output (227 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-armv7l-3.8
    creating build/lib.linux-armv7l-3.8/uvloop
    copying uvloop/_noop.py -> build/lib.linux-armv7l-3.8/uvloop
    copying uvloop/_patch.py -> build/lib.linux-armv7l-3.8/uvloop
    copying uvloop/_testbase.py -> build/lib.linux-armv7l-3.8/uvloop
    copying uvloop/__init__.py -> build/lib.linux-armv7l-3.8/uvloop
    running egg_info
    writing uvloop.egg-info/PKG-INFO
    writing dependency_links to uvloop.egg-info/dependency_links.txt
    writing top-level names to uvloop.egg-info/top_level.txt
    reading manifest file 'uvloop.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no previously-included files matching '*' found under directory 'vendor/libuv/.git'
    warning: no previously-included files matching '*' found under directory 'vendor/libuv/docs'
    warning: no previously-included files matching '*' found under directory 'vendor/libuv/img'
    writing manifest file 'uvloop.egg-info/SOURCES.txt'
    copying uvloop/cbhandles.pxd -> build/lib.linux-armv7l-3.8/uvloop
    copying uvloop/cbhandles.pyx -> build/lib.linux-armv7l-3.8/uvloop
    copying uvloop/dns.pyx -> build/lib.linux-armv7l-3.8/uvloop
    copying uvloop/errors.pyx -> build/lib.linux-armv7l-3.8/uvloop
    copying uvloop/loop.c -> build/lib.linux-armv7l-3.8/uvloop
    copying uvloop/loop.pxd -> build/lib.linux-armv7l-3.8/uvloop
    copying uvloop/loop.pyx -> build/lib.linux-armv7l-3.8/uvloop
    copying uvloop/lru.pyx -> build/lib.linux-armv7l-3.8/uvloop
    copying uvloop/pseudosock.pyx -> build/lib.linux-armv7l-3.8/uvloop
    copying uvloop/request.pxd -> build/lib.linux-armv7l-3.8/uvloop
    copying uvloop/request.pyx -> build/lib.linux-armv7l-3.8/uvloop
    copying uvloop/server.pxd -> build/lib.linux-armv7l-3.8/uvloop
    copying uvloop/server.pyx -> build/lib.linux-armv7l-3.8/uvloop
    copying uvloop/sslproto.pxd -> build/lib.linux-armv7l-3.8/uvloop
    copying uvloop/sslproto.pyx -> build/lib.linux-armv7l-3.8/uvloop
    creating build/lib.linux-armv7l-3.8/uvloop/handles
    copying uvloop/handles/async_.pxd -> build/lib.linux-armv7l-3.8/uvloop/handles
    copying uvloop/handles/async_.pyx -> build/lib.linux-armv7l-3.8/uvloop/handles
    copying uvloop/handles/basetransport.pxd -> build/lib.linux-armv7l-3.8/uvloop/handles
    copying uvloop/handles/basetransport.pyx -> build/lib.linux-armv7l-3.8/uvloop/handles
    copying uvloop/handles/check.pxd -> build/lib.linux-armv7l-3.8/uvloop/handles
    copying uvloop/handles/check.pyx -> build/lib.linux-armv7l-3.8/uvloop/handles
    copying uvloop/handles/handle.pxd -> build/lib.linux-armv7l-3.8/uvloop/handles
    copying uvloop/handles/handle.pyx -> build/lib.linux-armv7l-3.8/uvloop/handles
    copying uvloop/handles/idle.pxd -> build/lib.linux-armv7l-3.8/uvloop/handles
    copying uvloop/handles/idle.pyx -> build/lib.linux-armv7l-3.8/uvloop/handles
    copying uvloop/handles/pipe.pxd -> build/lib.linux-armv7l-3.8/uvloop/handles
    copying uvloop/handles/pipe.pyx -> build/lib.linux-armv7l-3.8/uvloop/handles
    copying uvloop/handles/poll.pxd -> build/lib.linux-armv7l-3.8/uvloop/handles
    copying uvloop/handles/poll.pyx -> build/lib.linux-armv7l-3.8/uvloop/handles
    copying uvloop/handles/process.pxd -> build/lib.linux-armv7l-3.8/uvloop/handles
    copying uvloop/handles/process.pyx -> build/lib.linux-armv7l-3.8/uvloop/handles
    copying uvloop/handles/stream.pxd -> build/lib.linux-armv7l-3.8/uvloop/handles
    copying uvloop/handles/stream.pyx -> build/lib.linux-armv7l-3.8/uvloop/handles
    copying uvloop/handles/streamserver.pxd -> build/lib.linux-armv7l-3.8/uvloop/handles
    copying uvloop/handles/streamserver.pyx -> build/lib.linux-armv7l-3.8/uvloop/handles
    copying uvloop/handles/tcp.pxd -> build/lib.linux-armv7l-3.8/uvloop/handles
    copying uvloop/handles/tcp.pyx -> build/lib.linux-armv7l-3.8/uvloop/handles
    copying uvloop/handles/timer.pxd -> build/lib.linux-armv7l-3.8/uvloop/handles
    copying uvloop/handles/timer.pyx -> build/lib.linux-armv7l-3.8/uvloop/handles
    copying uvloop/handles/udp.pxd -> build/lib.linux-armv7l-3.8/uvloop/handles
    copying uvloop/handles/udp.pyx -> build/lib.linux-armv7l-3.8/uvloop/handles
    creating build/lib.linux-armv7l-3.8/uvloop/includes
    copying uvloop/includes/__init__.py -> build/lib.linux-armv7l-3.8/uvloop/includes
    copying uvloop/includes/compat.h -> build/lib.linux-armv7l-3.8/uvloop/includes
    copying uvloop/includes/consts.pxi -> build/lib.linux-armv7l-3.8/uvloop/includes
    copying uvloop/includes/debug.h -> build/lib.linux-armv7l-3.8/uvloop/includes
    copying uvloop/includes/debug.pxd -> build/lib.linux-armv7l-3.8/uvloop/includes
    copying uvloop/includes/flowcontrol.pxd -> build/lib.linux-armv7l-3.8/uvloop/includes
    copying uvloop/includes/fork_handler.h -> build/lib.linux-armv7l-3.8/uvloop/includes
    copying uvloop/includes/python.pxd -> build/lib.linux-armv7l-3.8/uvloop/includes
    copying uvloop/includes/stdlib.pxi -> build/lib.linux-armv7l-3.8/uvloop/includes
    copying uvloop/includes/system.pxd -> build/lib.linux-armv7l-3.8/uvloop/includes
    copying uvloop/includes/uv.pxd -> build/lib.linux-armv7l-3.8/uvloop/includes
    running build_ext
    checking for a BSD-compatible install... /usr/bin/install -c
    checking whether build environment is sane... yes
    checking for a thread-safe mkdir -p... /bin/mkdir -p
    checking for gawk... no
    checking for mawk... mawk
    checking whether make sets $(MAKE)... yes
    checking whether make supports nested variables... yes
    checking build system type... armv7l-unknown-linux-gnueabihf
    checking host system type... armv7l-unknown-linux-gnueabihf
    checking for gcc... gcc
    checking whether the C compiler works... yes
    checking for C compiler default output file name... a.out
    checking for suffix of executables...
    checking whether we are cross compiling... no
    checking for suffix of object files... o
    checking whether we are using the GNU C compiler... yes
    checking whether gcc accepts -g... yes
    checking for gcc option to accept ISO C89... none needed
    checking whether gcc understands -c and -o together... yes
    checking for style of include used by make... GNU
    checking dependency style of gcc... gcc3
    checking if gcc supports -pedantic flag... yes
    checking for gcc way to treat warnings as errors... -Werror
    checking if gcc supports -fvisibility=hidden... yes
    checking if gcc supports -g flag... yes
    checking if gcc supports -std=gnu89 flag... yes
    checking if gcc supports -Wall flag... yes
    checking if gcc supports -Wextra flag... yes
    checking if gcc supports -Wno-long-long flag... yes
    checking if gcc supports -Wno-unused-parameter flag... yes
    checking if gcc supports -Wstrict-prototypes flag... yes
    checking for ar... ar
    checking the archiver (ar) interface... ar
    checking how to print strings... printf
    checking for a sed that does not truncate output... /bin/sed
    checking for grep that handles long lines and -e... /bin/grep
    checking for egrep... /bin/grep -E
    checking for fgrep... /bin/grep -F
    checking for ld used by gcc... /usr/bin/ld
    checking if the linker (/usr/bin/ld) is GNU ld... yes
    checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
    checking the name lister (/usr/bin/nm -B) interface... BSD nm
    checking whether ln -s works... yes
    checking the maximum length of command line arguments... 1572864
    checking whether the shell understands some XSI constructs... yes
    checking whether the shell understands "+="... yes
    checking how to convert armv7l-unknown-linux-gnueabihf file names to armv7l-unknown-linux-gnueabihf format... func_convert_file_noop
    checking how to convert armv7l-unknown-linux-gnueabihf file names to toolchain format... func_convert_file_noop
    checking for /usr/bin/ld option to reload object files... -r
    checking for objdump... objdump
    checking how to recognize dependent libraries... pass_all
    checking for dlltool... no
    checking how to associate runtime and link libraries... printf %s\n
    checking for archiver @FILE support... @
    checking for strip... strip
    checking for ranlib... ranlib
    checking command to parse /usr/bin/nm -B output from gcc object... ok
    checking for sysroot... no
    checking for mt... no
    checking if : is a manifest tool... no
    checking how to run the C preprocessor... gcc -E
    checking for ANSI C header files... yes
    checking for sys/types.h... yes
    checking for sys/stat.h... yes
    checking for stdlib.h... yes
    checking for string.h... yes
    checking for memory.h... yes
    checking for strings.h... yes
    checking for inttypes.h... yes
    checking for stdint.h... yes
    checking for unistd.h... yes
    checking for dlfcn.h... yes
    checking for objdir... .libs
    checking if gcc supports -fno-rtti -fno-exceptions... no
    checking for gcc option to produce PIC... -fPIC -DPIC
    checking if gcc PIC flag -fPIC -DPIC works... yes
    checking if gcc static flag -static works... yes
    checking if gcc supports -c -o file.o... yes
    checking if gcc supports -c -o file.o... (cached) yes
    checking whether the gcc linker (/usr/bin/ld) supports shared libraries... yes
    checking whether -lc should be explicitly linked in... no
    checking dynamic linker characteristics... GNU/Linux ld.so
    checking how to hardcode library paths into programs... immediate
    checking whether stripping libraries is possible... yes
    checking if libtool supports shared libraries... yes
    checking whether to build shared libraries... yes
    checking whether to build static libraries... yes
    checking whether make supports nested variables... (cached) yes
    checking for dlopen in -ldl... yes
    checking for kstat_lookup in -lkstat... no
    checking for gethostbyname in -lnsl... yes
    checking for perfstat_cpu in -lperfstat... no
    checking for pthread_mutex_init in -lpthread... yes
    checking for clock_gettime in -lrt... yes
    checking for sendfile in -lsendfile... no
    checking for socket in -lsocket... no
    checking for special C compiler options needed for large files... no
    checking for _FILE_OFFSET_BITS value needed for large files... 64
    checking sys/ahafs_evProds.h usability... no
    checking sys/ahafs_evProds.h presence... no
    checking for sys/ahafs_evProds.h... no
    checking that generated files are newer than configure... done
    configure: creating ./config.status
    config.status: creating Makefile
    config.status: creating libuv.pc
    config.status: executing depfiles commands
    config.status: executing libtool commands
      CC       src/libuv_la-fs-poll.lo
      CC       src/libuv_la-idna.lo
      CC       src/libuv_la-inet.lo
      CC       src/libuv_la-random.lo
      CC       src/libuv_la-strscpy.lo
      CC       src/libuv_la-threadpool.lo
      CC       src/libuv_la-timer.lo
      CC       src/libuv_la-uv-data-getter-setters.lo
      CC       src/libuv_la-uv-common.lo
      CC       src/libuv_la-version.lo
      CC       src/unix/libuv_la-async.lo
      CC       src/unix/libuv_la-core.lo
      CC       src/unix/libuv_la-dl.lo
      CC       src/unix/libuv_la-fs.lo
      CC       src/unix/libuv_la-getaddrinfo.lo
      CC       src/unix/libuv_la-getnameinfo.lo
      CC       src/unix/libuv_la-loop-watcher.lo
      CC       src/unix/libuv_la-loop.lo
      CC       src/unix/libuv_la-pipe.lo
      CC       src/unix/libuv_la-poll.lo
      CC       src/unix/libuv_la-process.lo
      CC       src/unix/libuv_la-random-devurandom.lo
      CC       src/unix/libuv_la-signal.lo
      CC       src/unix/libuv_la-stream.lo
      CC       src/unix/libuv_la-tcp.lo
      CC       src/unix/libuv_la-thread.lo
      CC       src/unix/libuv_la-tty.lo
      CC       src/unix/libuv_la-udp.lo
      CC       src/unix/libuv_la-linux-core.lo
      CC       src/unix/libuv_la-linux-inotify.lo
      CC       src/unix/libuv_la-linux-syscalls.lo
      CC       src/unix/libuv_la-procfs-exepath.lo
      CC       src/unix/libuv_la-proctitle.lo
      CC       src/unix/libuv_la-random-getrandom.lo
      CC       src/unix/libuv_la-random-sysctl.lo
      CC       src/unix/libuv_la-sysinfo-loadavg.lo
      CCLD     libuv.la
    ar: `u' modifier ignored since `D' is the default (see `U')
    building 'uvloop.loop' extension
    creating build/temp.linux-armv7l-3.8
    creating build/temp.linux-armv7l-3.8/uvloop
    gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I/data/venv/include -I/usr/local/include/python3.8 -I/tmp/pip-install-vdffozvt/uvloop/vendor/libuv/include -c uvloop/loop.c -o build/temp.linux-armv7l-3.8/uvloop/loop.o -O2
    gcc: fatal error: Killed signal terminated program as
    compilation terminated.
    error: command 'gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /data/venv/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-vdffozvt/uvloop/setup.py'"'"'; __file__='"'"'/tmp/pip-install-vdffozvt/uvloop/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-54ysa324/install-record.txt --single-version-externally-managed --compile --install-headers /data/venv/include/site/python3.8/uvloop Check the logs for full command output.
</details>

**Comment by bleonard252** [comment]
Works on a Pi 4. There might be a memory issue on the 3B+.

**Comment by PhasecoreX** [comment]
Yes, it's most likely a memory error from what I (and you) can tell. I don't have a 3B+ for testing, but I was able to run redbot with multiarch emulating an arm64v8 (the architecture 3B+ and 4 are using). The uvloop setup took probably like 15 minutes. Redbot did start successfully though, and subsequent runs where everything was up to date also started successfully.

There isn't much that I can do about this. If these packages were distributed as wheels, the install times will lower significantly (and not need to use ram for building). I'm not sure who does that wheel building and packaging though.

My suggestions would be to retry starting Redbot with as many containers/processes stopped as possible, or do the build on the Pi 4 and move your entire /data directory over to the 3B+ (assuming both would build the dependencies the same way with the same architecture). Either way once the first start/build is complete, it should be good to run other containers/processes.
