### ISSUE TITLE
Bad prefix

### ISSUE THREAD

**Issue by lbarnett83** [PhasecoreX/docker-red-discordbot#19]
Simple bug, not sure if fixable.  If you set the bot prefix to `*`, the bot will fail to start.  I don't know enough about docker to know if you can escape the prefix string so that you could use the `*` symbol as a prefix

Running latest version on Unraid 6.8.3

**Comment by PhasecoreX** [comment]
It is fixable! I'm slowly learning about the `set` command. Updated image is building at the moment...

**Comment by PhasecoreX** [comment]
Okay, pull the image and try again!
