### ISSUE TITLE
Custom cog not recognized

### ISSUE THREAD

**Issue by yhourdel** [PhasecoreX/docker-red-discordbot#21]
**Describe the bug**
My custom cog is not recognized and cannot be loaded.

**Run command**
```
docker-compose up
```

**Environment info:**
I am running Docker on macOS Catalina

**Additional context**
My custom cog is working good on another system without using Docker (using a standard red install).

**Comment by PhasecoreX** [comment]
Okay, I'll need a bit more information than that.

What is the full error you are getting in the logs when you try to load your custom cog?

What does your docker-compose.yml file look like?

Does your custom cog rely on any external dependencies that may not be in the docker image? (The error should show this if this is the case)

**Comment by yhourdel** [comment]
@PhasecoreX I found the issue, it's because I wasn't set as the bot owner so my loading commands were not accepted. So it's all my fault, but maybe you could add a line about this in the README?

**Comment by tgxn** [comment]
How did you end up setting the bot owner?

**Comment by PhasecoreX** [comment]
The bot owner is whoever created the bot "Application" in the [Discord Developer Portal](https://discord.com/developers/applications). So if you login with your Discord account and then create the application (bot), that bot wit that token will be owned by you.

**Comment by tgxn** [comment]
Heya mate,

I tried that but still when starting the container I was getting "there is no configured owner". I ended up using:
```
EXTRA_ARGS="--owner MY_DISCORD_ID"
```

**Comment by yhourdel** [comment]
In fact what I did is to add a few lines to main-loop.sh like this:

```
    if [ -n "${PREFIXES}" ]; then
        echo "Setting bot prefix(es)..."
        redbot docker --edit --no-prompt ${PREFIXES}
    fi

    # BEGIN added by me
    # configure owner if provided
    if [ -n "${OWNER:-}" ]; then
        echo "Setting bot owner..."
        redbot docker --edit --no-prompt --owner "${OWNER}"
    fi
    # END added by me

    echo "Starting Red-DiscordBot!"
```

and setting the `OWNER` env variable on the container, because I wasn't able to use the `EXTRA_ARGS` variable properly.

**Comment by yhourdel** [comment]
By the way @PhasecoreX tell me if you want me to do a PR for this.

**Comment by PhasecoreX** [comment]
I actually had EXACTLY that code already written yesterday, and just never pushed it lol. I can just commit and push it now, as another way to change the bot owner permanently (also I need to add it to the readme somewhere).
