### ISSUE TITLE
update

### ISSUE THREAD

**Issue by JacoVanR** [PhasecoreX/docker-red-discordbot#28]
**Describe the bug**
I can not update with this
**Run command**
```idk 
The Docker command/docker-compose.yml you are using to start the bot.
Be sure to censor your bot token (or any other sensitive info) if it is present!
```

**Environment info:**
What system are you running Docker on?
linux kernel 4.14.x

**Additional context**
Add any other context about the problem here. A more in-depth description, logs, screenshots, whatever.
none

**Comment by PhasecoreX** [comment]
What can you not update? The Docker image, the container startup bot update, or cogs?

Also you have provided zero logs, no examples, or anything to go off of, when I'm pretty sure I and many others are having no issues using the image.

**Comment by JacoVanR** [comment]
The update command does not work...


Op ma 28 dec. 2020 om 22:36 schreef Ryan Foster <notifications@github.com>:

**Comment by PhasecoreX** [comment]
So doing `[p]cog update` doesn't work? Is there any output or any logs generated when you try to run the command?

**Comment by JacoVanR** [comment]
i want to update the bot itself because it doen't work it doesn't respond
and the support team if i upgrade it it will work again.
[image: Knipsel.JPG]

Op di 29 dec. 2020 om 13:00 schreef Ryan Foster <notifications@github.com>:

**Comment by PhasecoreX** [comment]
The container, when starting up each time, will make sure that the bot software is up to date. If you just restart the container or the bot (with `[p]restart` in Discord) it will try to update to the latest bot version (version 3.4.5 at the time of writing). You can see this in the Docker logs.

**Comment by JacoVanR** [comment]
Ok ik will try it out thanks for the help

**Comment by JacoVanR** [comment]
it did not work


Op wo 30 dec. 2020 om 11:07 schreef sjakiedebanaan <vanrijnjaco09@gmail.com

**Comment by PhasecoreX** [comment]
I don't know how to help you. You have provided no information (logs, descriptions, how you run the container, etc.) besides "it did not work".

Plenty of people, myself included, can start the container and see the logs mention the Red-DiscordBot software being up to date. For example, a portion of my container logs from the last time I restarted says:

```
Installing collected packages: Red-DiscordBot
  Attempting uninstall: Red-DiscordBot
    Found existing installation: Red-DiscordBot 3.4.4
    Uninstalling Red-DiscordBot-3.4.4:
      Successfully uninstalled Red-DiscordBot-3.4.4
Successfully installed Red-DiscordBot-3.4.5
Starting Red-DiscordBot!
```

I will close this issue if you can't supply me the information I requested in the bug report template (additional context - logs, and run command - docker command or docker-compose.yml)
