### ISSUE TITLE
chatterbot library support

### ISSUE THREAD

**Issue by gitlimbo** [PhasecoreX/docker-red-discordbot#29]
Is it possible to have an image with support to [chatterbot](https://chatterbot.readthedocs.io/en/stable/setup.html)?

I want to use [this cog](https://github.com/bobloy/Fox-V3/tree/master/chatter), but adding the chatterbot pip install to the Dockerfile doesn't seem to work, and I'm not knowledgeable enough on docker to know why.

Thank you for this great docker.

**Comment by PhasecoreX** [comment]
I've gotten it to work before with this image. Red-DiscordBot uses its own library location for cog dependencies, so use the `[p]pipinstall` bot command to install the pip dependency instead of modifying the docker file.

**Comment by gitlimbo** [comment]
Oh right, It worked!
Thank you so much for this docker made my life so much easier to setup bots.
