### ISSUE TITLE
Weird timezone issue

### ISSUE THREAD

**Issue by Stonedestroyer** [PhasecoreX/docker-red-discordbot#4]
Hello, I am trying your docker and I think I got it right but I am getting a weird timezone issue.

```
root@machine:~# docker run -it --rm -v /mnt/user/appdata/redbot:/data -e TZ=Etc/UTC -e PUID=99 -e PGID=100 phasecorex/red-discordbot
cp: '/usr/share/zoneinfo/Etc/UTC' and '/etc/localtime' are the same file
failed to resize tty, using default size
```
I take it this is happening cause the timezone is same but not sure if this should be silenced or is a cause of user error. I wasn't aware the machine I was running it on was UTC but I see it solves the issue by not specifying timezone.

**Comment by PhasecoreX** [comment]
Yeah, I never thought to test with setting TZ=UTC (or Etc/UTC). As you have discovered, UTC would be the same as not setting the TZ environment variable at all. Regardless, I have fixed this in the image that this image is based off of, so once that is done building, this one will build and be pushed to Docker hub. It may take a while, as my CI server needs to rebuild many base images.

**Comment by PhasecoreX** [comment]
Alright this looks good to me now, thanks for reporting it!
