### ISSUE TITLE
Any chance of adding pytesseract for the OCR functions of the Retrigger COG

### ISSUE THREAD

**Issue by Fma965** [PhasecoreX/docker-red-discordbot#41]
**Is your feature request related to a problem? Please describe.**
Any chance of adding pytesseract for the OCR functions of the Retrigger COG, without this you can't use any OCR functions.

**Describe the solution you'd like**
Add the required packages as per https://github.com/TrustyJAID/Trusty-cogs/blob/master/retrigger/README.md#edit

**Describe alternatives you've considered**
I tried to get it to work myself but honestly i do C# and PHP etc not Python so i have no clue

Great work on this docker container, i love having everything as docker containers and the fact i can also do the same for red-discordbot is great :)

**Comment by PhasecoreX** [comment]
With ec8356b the full tag now has pytesseract-ocr, allowing for OCR things in ReTrigger to work. Be sure to do `[p]pipinstall pytesseract` manually, since it's not a required (and therefore automatically installed) package of ReTrigger.

**Comment by Fma965** [comment]
Awesome news, Thanks :)
