### ISSUE TITLE
Can't start container

### ISSUE THREAD

**Issue by kpostekk** [PhasecoreX/docker-red-discordbot#46]
**Describe the bug**
I have installed new instance of docker and I can't run redbot. Removing volume option doesn't change anything. I have the same behaviour while using `docker-compose`.

**Run command**
```
docker run -v /home/kpostek/redbotrun:/data -e TOKEN=redacted -e PREFIX=+ -e TZ=Europe/Warsaw phasecorex/red-discordbot:full
Timezone set to Europe/Warsaw
Starting with UID/GID: 1000/1000
Activating Python virtual environment...
Error: Command '['/data/venv/bin/python', '-Im', 'ensurepip', '--upgrade', '--default-pip']' returned non-zero exit status 1.
```

**Environment info:**
Linux fedora-p410 5.14.10-300.fc35.x86_64 #1 SMP Thu Oct 7 20:48:44 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
Docker version 20.10.12, build e91ed57
phasecorex/red-discordbot         audio             9915a9c10f74   2 weeks ago     613MB
phasecorex/red-discordbot         latest            9915a9c10f74   2 weeks ago     613MB
phasecorex/red-discordbot         full              faebe8b0144c   2 weeks ago     1.17GB

**Additional context**
I'm running this inside VM. I have tried all tags excluding `noaudio` and `convert-mongo-to-json`

**Comment by PhasecoreX** [comment]
Delete the `venv` folder inside of your /data mount and then you should be good.

**Comment by kpostekk** [comment]
Oh, sorry, my permission were quacked up. Sorry for minding you
