### ISSUE TITLE
[Errno 95] Operation not supported: 'lib' -> '/data/venv/lib64'

### ISSUE THREAD

**Issue by CrystalSpore** [PhasecoreX/docker-red-discordbot#55]
**Describe the bug**
On startup when attempting to migrate from a non-docker setup, I receive the error message matching the title of the post. Full output (all 3 lines of it) included in Run command below.

**Run command**
```
docker run -v /mnt/SporeBot_redbot/:/data -e TOKEN=********** -e PREFIX=! -e PUID=1000 -e PGID=1001 --name sporebot-redbot phasecorex/red-discordbot:latest
Starting with UID/GID: 1000/1001
Activating Python virtual environment...
Error: [Errno 95] Operation not supported: 'lib' -> '/data/venv/lib64'
```

**Environment info:**
```
uname -a
Linux machina 5.15.0-43-generic #46-Ubuntu SMP Tue Jul 12 10:30:17 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

**Additional context**
Full log included above. I did try deleting the venv folder, only to have it print the same message again. Only potential thing to mention is that `/mnt/SporeBot_redbot` is a cifs share, mounted with these options in `/etc/fstab`

```
//<IP_ADDRESS>/SporeBot_redbot /mnt/SporeBot_redbot cifs credentials=/etc/samba/credentials,_netdev,x-systemd.automount,uid=1000,gid=1001,file_mode=0777,dir_mode=0777,noperm 0 0
```

Share is mounted as expected
```
ls -lrt /mnt
drwxrwxrwx 2 snreloaded snreloaded    0 Aug  9 04:53 SporeBot_redbot
```

**Comment by CrystalSpore** [comment]
Turned out to be an issue with cifs not being configured to allow symlinks (a requirement for venv).

Jeff Geerling documented the solution [here](https://www.jeffgeerling.com/blog/2021/making-sure-symlinks-work-on-cifssmb-mounted-shares), but tldr is to add the `mfsymlinks` option to the cifs options list

**Comment by PhasecoreX** [comment]
Nice! Thank you for figuring this out!
