### ISSUE TITLE
Question about viewing the logs from within Discord itself

### ISSUE THREAD

**Issue by hollowstrawberry** [PhasecoreX/docker-red-discordbot#68]
I know this is likely beyond the scope of this image, but I would like to expose the output of the container to the bot owner through Discord, somehow. This is because sometimes something goes wrong and it doesn't get exposed with `[p]traceback`, and I'm not always in a position to SSH into the host machine.

I was thinking I could simply pipe the output to a file inside the container itself (and access it via an owner command of some kind), but I'm not experienced enough with Docker to know how. Could I get some guidance?

**Comment by PhasecoreX** [comment]
So normally Docker logs would be stored outside of the container, unless you somehow logged to a file and that file was saved to a volume somehow. Probably using the [logging configuration](https://docs.docker.com/compose/compose-file/compose-file-v3/#logging) somehow, though I don't see a way to specify a file name.

But! I think better would be to just use the log file that red itself generates at `/data/core/logs/latest.log`. Someone could cook up a cog that reads that file, or writes it to a channel or something.

**Comment by hollowstrawberry** [comment]
Oh, that's splendid, thanks. I'll look into it.

**Comment by PhasecoreX** [comment]
You're welcome! I'll close this then, since it's not specific to this Docker image.
