### ISSUE TITLE
Cogs are not loading

### ISSUE THREAD

**Issue by voaii** [PhasecoreX/docker-red-discordbot#69]
I did reinstalreqs and restarted

```
[ERROR] red: Package loading failed
Traceback (most recent call last):
File "/data/venv/lib/python3.11/site-packages/redbot/core/core_commands.py", line 188, in _load
await bot.load_extension(spec)
File "/data/venv/lib/python3.11/site-packages/redbot/core/bot.py", line 1686, in load_extension
await lib.setup(self)
TypeError: object NoneType can't be used in 'await' expression
```

**Comment by PhasecoreX** [comment]
How are you running the container? And do the default cogs load (downloader, general, etc.)? Could be whatever 3rd party cog you are trying to load doesn't support redbot 3.5.

**Comment by PhasecoreX** [comment]
You can use the [version freeze](https://github.com/PhasecoreX/docker-red-discordbot#version-freeze) environment variable to switch back to 3.4.19, though that could corrupt data if you've already switched to 3.5. But, if not even the alias cog is working that's a deeper problem.

Have you done `[p]cog reinstallreqs` yet? And you are running redbot version 3.5.1? (`[p]info`)

**Comment by PhasecoreX** [comment]
Yeah, though you might have to do `REDBOT_VERSION: ==3.4.19`

**Comment by PhasecoreX** [comment]
So weird... if you want you could also try deleting the `venv` folder and having the container reinstall redbot.

**Comment by PhasecoreX** [comment]
I also forgot, but you will have to use the `-py39` tagged images to use python 3.9 if you are sticking with redbot 3.4.

**Comment by PhasecoreX** [comment]
No, like `core-py39` or `extra-py39`. And I'm still confused how you have python 3.8 now, that's been out of the images for like a year now. You sure you're pulling the image and using that?

**Comment by Lifeismana** [comment]
That probably wouldn't work but you should try:

`image: phasecorex/red-discordbot:noaudio-py39` and `REDBOT_VERSION: ==3.4.19`

**Comment by PhasecoreX** [comment]
And just to verify again, only downloader cog loads and works, but alias/general/mod/admin cogs don't work?

If they do work then that makes sense, as 3rd party cogs will need to update for 3.5. If you have commissioned ones they would have to be updated. Sometimes as simple as just changing the `setup()` method to be async and then `await` the `bot.add_cog()` call.

**Comment by PhasecoreX** [comment]
How are you doing on this? If the included cogs work correctly and it's just some of your 3rd party ones aren't working, then that's not an issue with the Docker image and I will close this issue.

**Comment by PhasecoreX** [comment]
Haven't heard back, assuming this is just an issue with your custom cogs.
