### ISSUE TITLE
Invalid Token

### ISSUE THREAD

**Issue by jocon128** [PhasecoreX/docker-red-discordbot#7]
Starting Red-DiscordBot!
Red - Discord Bot | Configuration process

Please enter a valid token:
Traceback (most recent call last):
File "/data/venv/bin/redbot", line 10, in <module>
sys.exit(main())
File "/data/venv/lib/python3.7/site-packages/redbot/__main__.py", line 131, in main
new_token = interactive_config(red, token_set=bool(token), prefix_set=bool(prefix))
File "/data/venv/lib/python3.7/site-packages/redbot/core/cli.py", line 19, in interactive_config
token = input("> ")
EOFError: EOF when reading a line

Have tried deleting the persistence folder. Recreating the container. It is probably my setup but I am stuck.

**Comment by PhasecoreX** [comment]
Did you follow the First Time Setup in the readme? Specifically you need to run the image manually first to do the setup of the token.

Doing `docker run` with the `-it` will allow you to enter in the token properly. Then once the bot is set up, you can run it headless.

**Comment by PhasecoreX** [comment]
Okay so it turns out that only initial runs were not working, and subsequent ones would work just fine. I really need to test more...

Sorry about that! Hopefully this is all fixed up now. Let me know if there are any other issues!
