### ISSUE TITLE
Co-Owner Setup for bots that need multiple owners listed via ENV variables

### ISSUE THREAD

**Issue by Duke-Igthorn** [PhasecoreX/docker-red-discordbot#70]
Via command line it is possible to set multiple owner IDs for the bot to acknowledge as valid. The ENV variable only allows one OWNER to be set though.

It would be rad (and potentially easy to implement?!) to be able to define one or more co-owners via ENV variables.

**Comment by PhasecoreX** [comment]
You should be able to do this already... I can't find the regular documentation on this, but it should be as simple as defining it all in the `EXTRA_ARGS` environment variable. If it needs to be specified multiple times or there are spaces between them, you'd do something like `EXTRA_ARGS: --co-owner 12345` etc.

**Comment by Duke-Igthorn** [comment]
Oh well, that' great! I was utterly oblivious to that variable. 👀💦
I'll try it out and report back! Thanks so much!

**Comment by Duke-Igthorn** [comment]
Yup, works like a charm! Thanks for the heads up. :)

**Comment by PhasecoreX** [comment]
You're welcome!
