### ISSUE TITLE
Unable to load any 3rd party cogs

### ISSUE THREAD

**Issue by FireFtw** [PhasecoreX/docker-red-discordbot#71]
I couldn't say when it happened, but I've noticed my 3rd party cogs were unloaded. Attempting to load them gives an error.

I get a single error while loading:

>[2023-05-16 19:57:04] [INFO] red.Audio.WS.LLNode: Lavalink WS connecting to ws://10.0.0.10:2333 with headers {'Authorization': '***', 'User-Id': '***', 'Num-Shards': '1', 'Client-Name': 'Red-Lavalink/0.11.0', 'Resume-Key': 'Red-Core-Audio-458327308424577055-docker'}
>[2023-05-16 19:57:04] [INFO] red.Audio.WS.LLNode: Lavalink WS connected to ws://10.0.0.10:2333
>[2023-05-16 19:57:28] [INFO] red.main: SIGTERM received. Quitting...
>[2023-05-16 19:57:28] [INFO] red.main: Shutting down with exit code: 0 (SHUTDOWN)
>[2023-05-16 19:57:28] [INFO] red.Audio.WS.LLNode: [NODE] | Listener closing: None
>[2023-05-16 19:57:28] [INFO] red.Audio.WS.LLNode: Shutdown Lavalink WS.
>[2023-05-16 19:57:28] [INFO] red.main: Please wait, cleaning up a bit more
>Timezone set to America/Chicago
>Starting with UID/GID: 99/100
>Activating Python virtual environment...
>Updating Red-DiscordBot...
>Requirement already satisfied: wheel in /data/venv/lib/python3.11/site-packages (0.40.0)
>Requirement already satisfied: Red-DiscordBot in /data/venv/lib/python3.11/site-packages (3.5.2)
>Requirement already satisfied: aiodns==3.0.0 in /data/venv/lib/python3.11/site-packages (from Red-DiscordBot) (3.0.0)
>Requirement already satisfied: aiohttp==3.8.4 in /data/venv/lib/python3.11/site-packages (from Red-DiscordBot) (3.8.4)
>Requirement already satisfied: aiohttp-json-rpc==0.13.3 in /data/venv/lib/python3.11/site-packages (from Red-DiscordBot) (0.13.3)
>Requirement already satisfied: aiosignal==1.3.1 in /data/venv/lib/python3.11/site-packages (from Red-DiscordBot) (1.3.1)
>Requirement already satisfied: apsw==3.41.2.0 in /data/venv/lib/python3.11/site-packages (from Red-DiscordBot) (3.41.2.0)
>Requirement already satisfied: async-timeout==4.0.2 in /data/venv/lib/python3.11/site-packages (from Red-DiscordBot) (4.0.2)
>Requirement already satisfied: attrs==23.1.0 in /data/venv/lib/python3.11/site-packages (from Red-DiscordBot) (23.1.0)
>Requirement already satisfied: babel==2.12.1 in /data/venv/lib/python3.11/site-packages (from Red-DiscordBot) (2.12.1)
>Requirement already satisfied: brotli==1.0.9 in /data/venv/lib/python3.11/site-packages (from Red-DiscordBot) (1.0.9)
>Requirement already satisfied: cffi==1.15.1 in /data/venv/lib/python3.11/site-packages (from Red-DiscordBot) (1.15.1)
>Requirement already satisfied: charset-normalizer==3.1.0 in /data/venv/lib/python3.11/site-packages (from Red-DiscordBot) (3.1.0)
>Requirement already satisfied: click==8.1.3 in /data/venv/lib/python3.11/site-packages (from Red-DiscordBot) (8.1.3)
>Requirement already satisfied: contextlib2==21.6.0 in /data/venv/lib/python3.11/site-packages (from Red-DiscordBot) (21.6.0)
>Requirement already satisfied: discord-py==2.2.3 in /data/venv/lib/python3.11/site-packages (from Red-DiscordBot) (2.2.3)
>Requirement already satisfied: frozenlist==1.3.3 in /data/venv/lib/python3.11/site-packages (from Red-DiscordBot) (1.3.3)
>Requirement already satisfied: idna==3.4 in /data/venv/lib/python3.11/site-packages (from Red-DiscordBot) (3.4)
>Requirement already satisfied: importlib-metadata==6.6.0 in /data/venv/lib/python3.11/site-packages (from Red-DiscordBot) (6.6.0)
>Requirement already satisfied: markdown==3.4.3 in /data/venv/lib/python3.11/site-packages (from Red-DiscordBot) (3.4.3)
>Requirement already satisfied: markdown-it-py==2.2.0 in /data/venv/lib/python3.11/site-packages (from Red-DiscordBot) (2.2.0)
>Requirement already satisfied: mdurl==0.1.2 in /data/venv/lib/python3.11/site-packages (from Red-DiscordBot) (0.1.2)
>Requirement already satisfied: multidict==6.0.4 in /data/venv/lib/python3.11/site-packages (from Red-DiscordBot) (6.0.4)
>Requirement already satisfied: orjson==3.8.12 in /data/venv/lib/python3.11/site-packages (from Red-DiscordBot) (3.8.12)
>Requirement already satisfied: packaging==23.1 in /data/venv/lib/python3.11/site-packages (from Red-DiscordBot) (23.1)
>Requirement already satisfied: platformdirs==3.5.1 in /data/venv/lib/python3.11/site-packages (from Red-DiscordBot) (3.5.1)
>Requirement already satisfied: psutil==5.9.5 in /data/venv/lib/python3.11/site-packages (from Red-DiscordBot) (5.9.5)
>Requirement already satisfied: pycares==4.3.0 in /data/venv/lib/python3.11/site-packages (from Red-DiscordBot) (4.3.0)
>Requirement already satisfied: pycparser==2.21 in /data/venv/lib/python3.11/site-packages (from Red-DiscordBot) (2.21)
>Requirement already satisfied: pygments==2.15.1 in /data/venv/lib/python3.11/site-packages (from Red-DiscordBot) (2.15.1)
>Requirement already satisfied: python-dateutil==2.8.2 in /data/venv/lib/python3.11/site-packages (from Red-DiscordBot) (2.8.2)
>Requirement already satisfied: pytz==2023.3 in /data/venv/lib/python3.11/site-packages (from Red-DiscordBot) (2023.3)
>Requirement already satisfied: pyyaml==6.0 in /data/venv/lib/python3.11/site-packages (from Red-DiscordBot) (6.0)
>Requirement already satisfied: rapidfuzz==3.0.0 in /data/venv/lib/python3.11/site-packages (from Red-DiscordBot) (3.0.0)
>Requirement already satisfied: red-commons==1.0.0 in /data/venv/lib/python3.11/site-packages (from Red-DiscordBot) (1.0.0)
>Requirement already satisfied: red-lavalink==0.11.0 in /data/venv/lib/python3.11/site-packages (from Red-DiscordBot) (0.11.0)
>Requirement already satisfied: rich==13.3.5 in /data/venv/lib/python3.11/site-packages (from Red-DiscordBot) (13.3.5)
>Requirement already satisfied: schema==0.7.5 in /data/venv/lib/python3.11/site-packages (from Red-DiscordBot) (0.7.5)
>Requirement already satisfied: six==1.16.0 in /data/venv/lib/python3.11/site-packages (from Red-DiscordBot) (1.16.0)
>Requirement already satisfied: typing-extensions==4.5.0 in /data/venv/lib/python3.11/site-packages (from Red-DiscordBot) (4.5.0)
>Requirement already satisfied: yarl==1.9.2 in /data/venv/lib/python3.11/site-packages (from Red-DiscordBot) (1.9.2)
>Requirement already satisfied: zipp==3.15.0 in /data/venv/lib/python3.11/site-packages (from Red-DiscordBot) (3.15.0)
>Requirement already satisfied: uvloop==0.17.0 in /data/venv/lib/python3.11/site-packages (from Red-DiscordBot) (0.17.0)
>Requirement already satisfied: distro==1.8.0 in /data/venv/lib/python3.11/site-packages (from Red-DiscordBot) (1.8.0)
>Setting bot token...
>Setting bot prefix(es)...
>Starting Red-DiscordBot!
>[2023-05-16 19:58:05] [INFO] discord.client: logging in using static token
>[2023-05-16 19:58:06] [INFO] red: Loading packages...
>[2023-05-16 19:58:06] [WARNING] py.warnings: /data/cogs/CogManager/cogs/remindme/__init__.py:17: RuntimeWarning: coroutine 'Red.add_cog' was never awaited
>  bot.add_cog(cog)
>
>[2023-05-16 19:58:06] [INFO] red: Loaded packages: general, image, downloader, alias, remindme, cleanup, audio
>[2023-05-16 19:58:07] [INFO] discord.gateway: Shard ID 0 has connected to Gateway (Session ID: 3e27c223885307c2dd0ef653e6e043c6).
>[2023-05-16 19:58:07] [INFO] red: Connected to Discord. Getting ready...
>
>______         _           ______ _                       _  ______       _
>| ___ \       | |          |  _  (_)                     | | | ___ \     | |
>| |_/ /___  __| |  ______  | | | |_ ___  ___ ___  _ __ __| | | |_/ / ___ | |_
>|    // _ \/ _` | |______| | | | | / __|/ __/ _ \| '__/ _` | | ___ \/ _ \| __|
>| |\ \  __/ (_| |          | |/ /| \__ \ (_| (_) | | | (_| | | |_/ / (_) | |_
>\_| \_\___|\__,_|          |___/ |_|___/\___\___/|_|  \__,_| \____/ \___/ \__|
>
>╭───────── Chomosuke ──────────╮ ╭─────────────────────╮
>│  Prefixes           │ !      │ │  Shards       │ 1   │
>│  Language           │ en-US  │ │  Servers      │ 1   │
>│  Red version        │ 3.5.2  │ │  Unique Users │ 16  │
>│  Discord.py version │ 2.2.3  │ ╰─────────────────────╯
>│  Storage type       │ JSON   │                        
>╰──────────────────────────────╯                        
>Loaded 8 cogs with 90 commands

And then while trying to load a cog I get a similar error.

>2023-05-16 20:02:28] [WARNING] py.warnings: /data/cogs/CogManager/cogs/wikipedia/__init__.py:16: RuntimeWarning: coroutine >'Red.add_cog' was never awaited
>  bot.add_cog(cog)
>
>[2023-05-16 20:02:28] [ERROR] red: Package loading failed
>Traceback (most recent call last):
>  File "/data/venv/lib/python3.11/site-packages/redbot/core/core_commands.py", line 188, in _load
>    await bot.load_extension(spec)
>  File "/data/venv/lib/python3.11/site-packages/redbot/core/bot.py", line 1686, in load_extension
>    await lib.setup(self)
>TypeError: object NoneType can't be used in 'await' expression

while the 'remindme' cog says it's enabled the bot never responds. As far as I can tell all the other loaded cogs are working as expected.

**Comment by PhasecoreX** [comment]
Make sure you update your cogs with `[p]cog update`. The update to redbot 3.5 is a breaking change for 3rd party cogs, which the error above reflects. All of my cogs are updated, so I know the above error with Wikipedia cog would not happen.

**Comment by FireFtw** [comment]
> Make sure you update your cogs with `[p]cog update`. The update to redbot 3.5 is a breaking change for 3rd party cogs, which the error above reflects. All of my cogs are updated, so I know the above error with Wikipedia cog would not happen.

Well I feel dumb, didn't even notice there was a manual way to update them. Thanks!
