### ISSUE TITLE
Bot has no commands

### ISSUE THREAD

**Issue by nfp0** [PhasecoreX/docker-red-discordbot#86]
**Describe the bug**
After creating a Bot following the intructions [here](https://docs.discord.red/en/stable/bot_application_guide.html) and following this repository's README instructions in detail, the bot shows up on the server, but it has no commands.

All the 3 "Privileged Gateway Intents" are enabled.

This is it's configuration on the Discord Server:

![image](https://github.com/PhasecoreX/docker-red-discordbot/assets/11202422/47a83ba9-b586-40ea-9c89-bb7a64827081)

I have also tried it on a brand new Discord Server with all the default settings, but the same behavior occurs.
I'm not sure what I'm doing wrong.

The container output with --debug enabled is the following:

```
Setting bot token...
Setting bot prefix(es)...
Starting Red-DiscordBot!
/data/venv/lib/python3.11/site-packages/discord/player.py:28: DeprecationWarning: 'audioop' is deprecated and slated for removal in Python 3.13
  import audioop
[2024-03-14 11:35:03] [DEBUG] red.main: ====Basic Config====
[2024-03-14 11:35:03] [DEBUG] red.main: Data Path: /data
[2024-03-14 11:35:03] [DEBUG] red.main: Storage Type: JSON
[2024-03-14 11:35:03] [INFO] discord.client: logging in using static token
[2024-03-14 11:35:03] [INFO] red: No packages were loaded.
[2024-03-14 11:35:04] [INFO] discord.gateway: Shard ID 0 has connected to Gateway (Session ID: my_session_id).
[2024-03-14 11:35:04] [INFO] red: Connected to Discord. Getting ready...

______         _           ______ _                       _  ______       _
| ___ \       | |          |  _  (_)                     | | | ___ \     | |
| |_/ /___  __| |  ______  | | | |_ ___  ___ ___  _ __ __| | | |_/ / ___ | |_
|    // _ \/ _` | |______| | | | | / __|/ __/ _ \| '__/ _` | | ___ \/ _ \| __|
| |\ \  __/ (_| |          | |/ /| \__ \ (_| (_) | | | (_| | | |_/ / (_) | |_
\_| \_\___|\__,_|          |___/ |_|___/\___\___/|_|  \__,_| \____/ \___/ \__|

╭──────── K.K. Slider ─────────╮ ╭─────────────────────╮
│  Prefixes           │ .      │ │  Shards       │ 1   │
│  Language           │ en-US  │ │  Servers      │ 1   │
│  Red version        │ 3.5.5  │ │  Unique Users │ 14  │
│  Discord.py version │ 2.3.2  │ ╰─────────────────────╯
│  Storage type       │ JSON   │                        
╰──────────────────────────────╯                        
Loaded 2 cogs with 41 commands

```

**Run command**
```
docker run -v red-discordbot:/data -e TOKEN=my_token -e PREFIX=. -e EXTRA_ARGS="--debug" phasecorex/red-discordbot
```

**Environment info:**

Tested on 2 systems:
- Arch Linux on kernel 6.6.18-1-lts
- Manjaro on kernel 6.7.7-1-MANJARO

**Comment by PhasecoreX** [comment]
If you do `[p]help`, nothing shows up? You have to `[p]load` cogs in order to start using them, for example `[p]load Downloader`. `[p]cogs` will show you all of the available and loaded cogs.

**Comment by nfp0** [comment]
I'll be damned, that indeed works! Thanks!

But the commands don't show up on the auto-complete list, like other bots. Shouldn't they be listed?
And why does the integration menu still say that the bot has no commands? Is that the expected behavior?

**Comment by PhasecoreX** [comment]
Redbot by default doesn't have slash commands. Some third party cogs will have slash command support, but you would need to enable them with the `[p]slash` command. I don't think any of the built in cogs have slash commands.

**Comment by nfp0** [comment]
Got it. Thanks for the help!
