### ISSUE TITLE
The formatting of steps.

### ISSUE THREAD

**Issue by Scary-Guy** [PhasecoreX/docker-red-discordbot#94]
So, I go through the quick start:
```
Just do this:

docker run -v /local_folder_for_persistence:/data -e TOKEN=bot_token -e PREFIX=. phasecorex/red-discordbot
```

Oh it's not working, I wonder why it's not working.  Let me read further.
```
Red-DiscordBot will start up with the specified token and prefix, and after updating, it will show the invite URL. Use this to add the bot to your server.
```

Okay, I admit it's partly on me for being lazy and not reading ahead, but the wording "just do this" made it sound like that's all I had to do for the first step.  If the second thing were put in front of the first thing, or if something like "after modifying the string" I wouldn't be having an issue.

**Comment by PhasecoreX** [comment]
I mean, you also would have to update the `/local_folder_for_persistence` too. But I guess that could just work when blindly copied and run, as Docker would make a root level directory.

I have updated the readme to fix that, and to tell the user what two things are required to be updated (data path and bot token).
